-- Migration 009: Separate S and M pizza sizes
DO $$
BEGIN
    -- Update original item to be Size M
    UPDATE menu_items SET name = '4 Cheeses M', price = 16.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'eae62d37-1b2b-4f38-9eda-6b3b39baa5ca';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), '4 Cheeses S', 'Sauce tomate, mozzarella, chèvre, gorgonzola, emmental', 12, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/2j4119zpzg.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 3);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Chevre Miel M', price = 16.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '15422254-1248-48e5-9b47-922a6e0c5446';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Chevre Miel S', 'Sauce tomate, chèvre, miel', 12, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/ol3vq58jk8h.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 6);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Savoyarde M', price = 20, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '2fd4a4b3-d811-4757-a318-b44f6459eb4b';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Savoyarde S', 'Sauce crème, pommes de terre, reblochon, bacon, origan', 15.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/7p0z4mlu3po.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 7);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'BBQ Chicken M', price = 17.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '594837b2-861e-46dd-b3b7-038712392458';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'BBQ Chicken S', 'Sauce tomate, poulet, oignons, poivrons, swirl BBQ', 13, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/15peyh3jx5q.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 15);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Tonno M', price = 19.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '5519523d-5e44-434f-93c1-3dc2fd5f6f18';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Tonno S', 'Sauce tomate, thon, oignons, olives noires', 15, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/fx69efbutyd.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 19);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Margherita Mania M', price = 15, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'c560c4f0-1aae-4670-974d-d732e8cd172a';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Margherita Mania S', 'Sauce tomate, mozzarella, olives noires, origan', 10.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/j7yb4ehh369.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 1);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Chicken Kebab M', price = 20, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '6b31304a-0bca-4a99-a3bf-8c5a2074f73f';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Chicken Kebab S', 'Sauce tomate, kebab, oignons, poivrons, swirl samouraï', 15.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/cmfxzaoddwi.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 11);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Toscane M', price = 18, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'fdd0a0ee-2148-4940-9f10-2d90ba740ed9';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Toscane S', 'Sauce tomate, mozzarella jambon', 13.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/icl96yiri7g.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 8);

    -- Update original item to be Size M
    UPDATE menu_items SET name = '4 Saisons M', price = 19.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '60adb8a0-854b-4e70-bb05-6b33876ab04a';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), '4 Saisons S', 'Sauce tomate, mozzarella, jambon, champignons, artichauts, olives', 15, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/3064jq32lvo.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 9);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Peperroni Mania M', price = 15.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '02b5fe4a-bf20-4f5c-a8fb-e511b7b53104';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Peperroni Mania S', 'Sauce tomate, pepperoni, mozzarella', 11, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/zhfi4sd5hdn.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 10);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Hannibal M', price = 17.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '6ffb0c29-c85b-4a08-ba92-3c65d80e0b04';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Hannibal S', 'Sauce barbecue, mozzarella, poulet, merguez, boeuf', 13, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/8bajrbebsl.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 12);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Creamy Mania M', price = 21, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'a2c314da-0e79-4b7f-a9ff-70928db48801';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Creamy Mania S', 'Sauce crème, champignons, oignons, pepperoni, merguez, poulet, ail', 16.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/p49yucp5uzk.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 14);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'BBQ Grill M', price = 20, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'b7f1aabb-2575-4822-8a1d-52c01658668f';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'BBQ Grill S', 'Sauce BBQ, mozzarella, bacon, boeuf, oignons, swirl BBQ', 15.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/w20vyjdy2j.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 16);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Scampi M', price = 18, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '1904a24e-bd7d-466a-8e20-1654e2dc4ed7';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Scampi S', 'Sauce tomate, scampi, huile à l''ail maison', 13.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/jpt6f2eu6xo.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 17);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Saumon M', price = 21, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'e79b66d9-22e2-440f-9b6d-818e7e8edc14';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Saumon S', 'Sauce tomate saumon oignon sauce crème', 16.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/w7wdwtq1e4.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 18);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Funghi M', price = 15, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '19e3ea5c-be69-46a4-abfe-41ac0fc7bcc5';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Funghi S', 'Sauce tomate, mozzarella, champignons, origan', 10.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/362nituyirt.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 4);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Veggie Mania M', price = 15.5, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '91ee531e-150f-4466-b07b-56f124da5d66';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Veggie Mania S', 'Sauce tomate, mozzarella, olives, oignons, poivrons, tomate, champignons, artichauts, origan', 11, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/dede1fkfhxp.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 2);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Creamy 4 Cheeses M', price = 20, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = 'af342e69-3d13-4dc2-929b-740953d41165';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Creamy 4 Cheeses S', 'Sauce crème, mozzarella, emmental, chèvre, gorgonzola, origan', 15.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/igl5jkkb5qd.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 5);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Hot Mania M', price = 17, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '9f33f563-f567-4d1d-8074-2847d61e729f';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Hot Mania S', 'Sauce tomate, mozzarella, merguez, pepperoni, champignons, piment swirl algérienne', 12.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/pa202hqqaw.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 13);

    -- Update original item to be Size M
    UPDATE menu_items SET name = 'Forestiere M', price = 19, options = '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb WHERE id = '159704d5-884a-44f7-b208-83ea83cf8e86';

    -- Insert new item for Size S
    INSERT INTO menu_items (id, name, description, price, category_id, image_url, is_available, is_featured, options, sort_order)
    VALUES (gen_random_uuid(), 'Forestiere S', 'Sauce tomate, mozzarella, jambon, champignons, bacon', 14.5, '70f9ab31-e1b8-4bb1-b3e6-432b28287455', 'https://qdqrtfjfnxgvqrgomrls.supabase.co/storage/v1/object/public/assets/menu-items/s97lmtchzf.webp', true, false, '[{"name":"Supplement Sauce","type":"single","choices":[{"name":"Bbq swirl","price_addition":0.5},{"name":"Algérienne swirl","price_addition":0.5},{"name":"Ail","price_addition":0.5},{"name":"Samurai","price_addition":0.5},{"name":"Huile à l''ail maison","price_addition":0}],"required":false},{"name":"Extra Ingredients","type":"multiple","choices":[{"name":"Chevre","price_addition":1.5},{"name":"Parmesan","price_addition":1.5},{"name":"Gorgonzola","price_addition":1.5},{"name":"Emmental","price_addition":1.5},{"name":"Poulet","price_addition":2},{"name":"Boeuf","price_addition":2},{"name":"Bacon","price_addition":1.5},{"name":"Ananas","price_addition":1},{"name":"Capre","price_addition":1},{"name":"Jambon","price_addition":1.5},{"name":"Merguez","price_addition":2},{"name":"Kebab","price_addition":2},{"name":"Bolognaise","price_addition":2},{"name":"Scampis","price_addition":3},{"name":"Saumon","price_addition":3},{"name":"Fruit de Mer","price_addition":3.5},{"name":"Oeuf","price_addition":1},{"name":"Extra Mozzarella","price_addition":1.5}],"required":false}]'::jsonb, 20);

END $$;
